# Generated by Django 3.2.5 on 2021-07-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cursoaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cursos',
            field=models.ManyToManyField(through='core.CursoAluno', to='core.Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(through='core.CursoAluno', to='core.Aluno'),
        ),
    ]
