# Generated by Django 3.2.5 on 2021-07-02 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210701_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='tx_descricao', max_length=40, unique=True)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado_civil',
            field=models.ForeignKey(blank=True, db_column='id_estado_civil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadocivil'),
        ),
    ]
