# Generated by Django 3.2.5 on 2021-07-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.ForeignKey(blank=True, db_column='id_estado_civil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alunos', to='core.estadocivil'),
        ),
    ]
